spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8004

dubbo:
  application:
    name: user-provider
  registry:
    address: zookeeper://ylnzk.cn:2181
  protocol:
    name: dubbo
    port: 20881